process.env.NODE_ENV = 'test';
process.env.PORT = '5001';
process.env.DB_HOST = process.env.DB_HOST || 'localhost';
process.env.DB_PORT = process.env.DB_PORT || '3306';
process.env.DB_NAME = process.env.DB_NAME || 'job_scheduler_test';
process.env.DB_USER = process.env.DB_USER || 'jobscheduler';
process.env.DB_PASSWORD = process.env.DB_PASSWORD || 'jobscheduler_password';
process.env.JWT_ACCESS_SECRET = process.env.JWT_ACCESS_SECRET || 'test_access_secret_please_replace';
process.env.JWT_REFRESH_SECRET = process.env.JWT_REFRESH_SECRET || 'test_refresh_secret_please_replace';
